### ISSUE TITLE
Doesnt seem to be working on OC 0.6.6 with latest OpenCanopy. 

### ISSUE THREAD

**Issue by alejoacostaa** [tekteq/opencanopy-minimal-theme#1]
Doesnt seem to be working on OC 0.6.6 with latest OpenCanopy. 

Replaced all files in /Resources/Image + set PickerAttributes to 1 and it defaulted to the usual OpenCanopy icons.

**Comment by frankovich** [comment]
All works. Mistakes on your side.

**Comment by Just-a-Cactus** [comment]
> Doesnt seem to be working on OC 0.6.6 with latest OpenCanopy.
> 
> Replaced all files in /Resources/Image + set PickerAttributes to 1 and it defaulted to the usual OpenCanopy icons.

All works. Mistakes on your side.

**Comment by ZeroShadowX** [comment]
I also seem to be having trouble as well. Worked fine on 0.6.5 but after updating and following the steps its not working on 0.6.6. I also went back to 0.6.5 and repeated all the steps and it worked tried it again on 0.6.6 and can't get it to work. In my case I get the text selection not the icons at all. I'll keep playing with it and if I figure it out will report back.

**Comment by dmikhalsky** [comment]
Is this the reason?

_ Yeah, this seems to be catching a few people out. OpenCanopy now looks for Left.icns and Right.icns to support the new scroll function, and bails if it doesn’t find them._

https://www.insanelymac.com/forum/topic/346591-text-entry-picker-instead-of-icons-gui-in-opencore-066/

**Comment by ZeroShadowX** [comment]
Confirmed that this does in fact work if you add the left and right incs into the resource folder. In the included link that @dmikhalsk mentioned you will find a github link that has the updated icns files that you could include in your github @frankovich and that will fix it for anyone else that may download your theme. 

Thanks for the theme and the help @dmikhalsky

**Comment by sXmpwn** [comment]
How can I get this to work? Can someone share me his EFI so I can look how this works? Thanks

**Comment by sXmpwn** [comment]
> Confirmed that this does in fact work if you add the left and right incs into the resource folder. In the included link that @dmikhalsk mentioned you will find a github link that has the updated icns files that you could include in your github @frankovich and that will fix it for anyone else that may download your theme.
> 
> Thanks for the theme and the help @dmikhalsky

can you help me?

**Comment by dmikhalsky** [comment]
@ad422 download Resources folder for OC version above 0.6.6 and copy right.incs and left.incs icons to your EFI folder

**Comment by tekteq** [comment]
added the two .incs files to the git thanks for letting me know!
